version: '2'
services:
  tcpwrapper:
    build:
      context: .
    stdin_open: true
    volumes:
      - ./hosts.allow:/app/hosts.allow
    restart: always
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    stdin_open: true
    links:
      - tcpwrapper
    restart: always
